In [9]:
from IPython.core.display import display, HTML
display(HTML(
"""<style>
div.container { width:100% !important; }
div.CodeMirror {font-family: Consolas; font-size: 25pt;}
div.output { font-size: 20pt; font-weight: bold;}
div.input { font-family: Consolas; font-size: 25pt;}
div.prompt { min-width: 100px;}
</style>
"""))

C:\Users\songs\AppData\Local\Temp\ipykernel_17460\627556072.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [8]:
result = 10
def test_result(n):
    global result
    result += n

In [29]:
print(result)
test_result(100)
print(result)

10
110


In [7]:
result1 = 10
def test_result1(n):
    global result1
    result1 += n
    #return result1

test_result1(3)
print(result1)

13


In [33]:
print(result)
print(result1)
test_result1(200)
print(result1)

110
10
210


In [35]:
print(result)
print(result1)

110
210


In [37]:
result2 = 10
def test_result2(n):
    global result2
    result2 += n

In [38]:
print(result)
print(result1)
print(result2)

110
210
10


In [39]:
test_result(10)
print(result)

120


In [40]:
print(result1)
print(result2)

210
10


In [42]:
class ClasTest:
    result = 10
    def test_result(self, n):
        self.result += n

In [43]:
a1 = ClasTest() # result, test_result()
a1.result
a1.test_result(10)

10

In [44]:
a2 = ClasTest()
a2.result = 100
print(a1.result)
print(a2.result)

10
100


In [54]:
class Men:
    name = '' ### 멤버필드 , 멤버변수
    age = 0
    def setVal(self, name, age): # 멤버메서드
        self.name = name
        self.age = age
    def add(self):
        return self.name
        
def add(num1, num2): # 함수
    print(num1 + num2)

In [58]:
rhee = Men()
rhee.setVal('이숭무', 40)
a = rhee.add()
print(rhee.name)

이숭무


In [47]:
park = Men()
park.setVal('박준현', 35)

In [49]:
print(rhee.name)
print(park.name)

이숭무
박준현


In [65]:
class FourCal:
    #first = 0
    #second = 0
    #result = 0
    def setData(self, first, second):
        self.first = first
        self.second = second
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second    

In [ ]:
cal = FourCal()
cal.setData(10,20)
cal.add()
print(cal.result)
cal.div()
print(cal.result)

In [69]:
cal1 = FourCal()
cal1.setData(10,30)

In [70]:
cal2 = FourCal()
FourCal.setData(cal2, 20, 40)
print(cal2.first)

20


In [71]:
class FourCal:
    def add(self, num1, num2):
        self.result = num1 + num2
    def div(self, num1, num2):
        self.result = num1 + num2        

In [72]:
cal3 = FourCal()
#FourCal.add(cal3, 10, 20)
cal3.add(10, 20) 
print(cal3.result)

30


In [75]:
cal4 = FourCal()
FourCal.add(cal4, 10, 20)
print(cal4.result)
cal4.add(10, 30)

30


In [83]:
class FourCal:
    def setData(self, first, second): # 멤버필드를 초기화
        self.first = first
        self.second = second
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second  

In [88]:
cal1 = FourCal()
cal1.setData(10, 20)
print(cal1.first)
print(cal1.second)
cal1.add()
print(cal1.result)

10
20
30


In [90]:
class FourCal:
    def __init__(self, first, second): # 생성자:멤버필드를 초기화 하기 위해서
        self.first = first
        self.second = second
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second  

In [91]:
cal1 =  FourCal(10, 20)
print(cal1.first)
print(cal1.second)
cal1.add()
print(cal1.result)

10
20
30


In [93]:
##cal1 =  FourCal() # 생성자가 있는 경우에는 무조간 초기값을 주어야 한다.

In [97]:
class MoreFourCal(FourCal):
    '''
    def __init__(self, first, second): # 생성자:멤버필드를 초기화 하기 위해서
        self.first = first
        self.second = second
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second
    '''
    def sub(self):
        self.result = self.first - self.second 
    def mul(self):
        self.result = self.first * self.second 

In [98]:
cal5 = MoreFourCal(10, 20);
cal5.add()
print(cal5.result)
cal5.mul()
print(cal5.result)

30
200


In [99]:
cal6 = MoreFourCal(0, 20)
cal6.div() # 0 / 20 = 0 : 부정
print(cal6.result)

0.0


In [100]:
cal7 = MoreFourCal(20, 0)
cal7.div() # 20 / 0 :  불능 

ZeroDivisionError: division by zero

In [114]:
class MoreFourCal(FourCal):
    def sub(self):
        self.result = self.first - self.second 
    def mul(self):
        self.result = self.first * self.second
    def div(self): # 재정의 : override
        if self.second == 0:
            self.result = 0
        else:
            self.result = self.first / self.second

In [103]:
cal8 = MoreFourCal(20, 0)
cal8.div()
print(cal8.result)
# 클래스의 구성 요소 : 멤버필드(멤버변수), 메서드, 생성자
# 메서드에는 self
# 멤버필드를 초기화 : 생성자
# 상속 : 다른 클래스에 정의된 걸 가지고 온는것
# 상속받은 메서드를 다시 정의 : override

0


In [104]:
# 모듈 : 변수, 상수 , 함수, 클래스, 객체등을 모아 둔 파일 
import mod1
print(mod1.PI)

3.141592


In [107]:
cal10 = mod1.MoreFourCal(30, 50)
cal10.add()
print(cal10.result)
result = mod1.sum1(100, 30)
print(result)

80
130


In [108]:
import random
n = random.randint(1, 10)
print(n)

5


In [109]:
from random import *
n = randint(1, 10)
print(n)

2


In [110]:
from mod1 import *
a = sum1(200,200)
print(a)

400


In [ ]:
### 스크래핑 : 웹 문서에 있는 코드 모두를 다 가지고 오는 것
### 크롤링 : 스크래핑한 코드에서 원하는 내용만 추출해오는 것

In [116]:
# 스크래핑
import urllib.request
url = "http://uta.pw/shodou/img/28/214.png"
filesave =  "test.png"
urllib.request.urlretrieve(url,filesave)

('test.png', <http.client.HTTPMessage at 0x1d42b579ed0>)

In [119]:
import urllib.request
url = "http://uta.pw/shodou/img/28/214.png"
mem = urllib.request.urlopen(url).read()
#print(mem)
with open("test1.png", "wb") as f:
    f.write(mem)

In [121]:
url = "http://api.aoikujira.com/ip/ini"
mem = urllib.request.urlopen(url).read()
print(mem)
text = mem.decode("utf-8")
print(text)

b'[ip]\nAPI_URI=http://api.aoikujira.com/ip/get.php\nREMOTE_ADDR=121.160.41.224\nREMOTE_HOST=121.160.41.224\nREMOTE_PORT=56316\nHTTP_HOST=api.aoikujira.com\nHTTP_USER_AGENT=Python-urllib/3.11\nHTTP_ACCEPT_LANGUAGE=\nHTTP_ACCEPT_CHARSET=\nSERVER_PORT=80\nFORMAT=ini\n\n'
[ip]
API_URI=http://api.aoikujira.com/ip/get.php
REMOTE_ADDR=121.160.41.224
REMOTE_HOST=121.160.41.224
REMOTE_PORT=56316
HTTP_HOST=api.aoikujira.com
HTTP_USER_AGENT=Python-urllib/3.11
HTTP_ACCEPT_LANGUAGE=
HTTP_ACCEPT_CHARSET=
SERVER_PORT=80
FORMAT=ini




In [125]:
### https://search.naver.com/search.naver?ie=utf8&query=python
#  |<-                                                     ->| url
#                           |<-                            ->| uri
#                                        |<-               ->|쿼리 스트링
import urllib.request
import urllib.parse
API = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108"
data = urllib.request.urlopen(API).read()
text = data.decode("utf-8")
print(text)

<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0">
<channel>
<title>기상청 육상 중기예보</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</link>
<description>기상청 날씨 웹서비스</description>
<language>ko</language>
<generator>기상청</generator>
<pubDate>2023년 08월 05일 (토)요일 06:00</pubDate>
 <item>
<author>기상청</author>
<category>육상중기예보</category>
<title>전국 육상 중기예보 - 2023년 08월 05일 (토)요일 06:00 발표</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</link>
<guid>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</guid>
<description>
	<header>
		<title>전국 육상중기예보</title>
		<tm>202308050600</tm>
		<wf><![CDATA[○ (강수) 8일(화) 강원영동에, 9일(수)~10일(목) 강원영동과 경상권에 비가 오겠습니다.<br />○ (기온) 8일(화)~9일(수) 아침 기온은 24~27도, 낮 기온은 28~35도로 평년(최저기온 22~24도, 최고기온 29~33도)보다 높겠습니다.<br />          10일(목)~15일(화) 아침 기온은 22~26도, 낮 기온은 29~33도로 평년과 비슷하겠습니다.<br />○ (해상) 제주도해상은 9일(수)까지, 남해동부해상은 10일(목)까지 물결이 1.0~4.0m(남해동부해상 9일(수) 5.0m 이상)로 매우 높게 일겠으며, <br />          동해상은 8일(화)~11일(금) 물결이 1.0~4.0m(9일(수)~1

In [126]:
import urllib.request
import urllib.parse
API = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
value = {"stnId": 108}
params = urllib.parse.urlencode(value) # 딕셔너리 => 쿼리스트링
url = API + "?" + params;
data = urllib.request.urlopen(API).read()
text = data.decode("utf-8")
print(text)

<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0">
<channel>
<title>기상청 육상 중기예보</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</link>
<description>기상청 날씨 웹서비스</description>
<language>ko</language>
<generator>기상청</generator>
<pubDate>2023년 08월 05일 (토)요일 06:00</pubDate>
 <item>
<author>기상청</author>
<category>육상중기예보</category>
<title>전국 육상 중기예보 - 2023년 08월 05일 (토)요일 06:00 발표</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</link>
<guid>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</guid>
<description>
	<header>
		<title>전국 육상중기예보</title>
		<tm>202308050600</tm>
		<wf><![CDATA[○ (강수) 8일(화) 강원영동에, 9일(수)~10일(목) 강원영동과 경상권에 비가 오겠습니다.<br />○ (기온) 8일(화)~9일(수) 아침 기온은 24~27도, 낮 기온은 28~35도로 평년(최저기온 22~24도, 최고기온 29~33도)보다 높겠습니다.<br />          10일(목)~15일(화) 아침 기온은 22~26도, 낮 기온은 29~33도로 평년과 비슷하겠습니다.<br />○ (해상) 제주도해상은 9일(수)까지, 남해동부해상은 10일(목)까지 물결이 1.0~4.0m(남해동부해상 9일(수) 5.0m 이상)로 매우 높게 일겠으며, <br />          동해상은 8일(화)~11일(금) 물결이 1.0~4.0m(9일(수)~1

In [132]:
import urllib.request
import urllib.parse
regionNumber = int(input("지역번호를 입력하세요. "))
API = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
value = {"stnId": regionNumber}
params = urllib.parse.urlencode(value) # 딕셔너리 => 쿼리스트링
url = API + "?" + params;
print(url)
data = urllib.request.urlopen(API).read()
text = data.decode("utf-8")
#print(text)

지역번호를 입력하세요. 108
http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108


In [ ]:
API = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
value = {"stnId": 108}
params = urllib.parse.urlencode(value) # 딕셔너리 => 쿼리스트링
url = API + "?" + params;
data = urllib.request.urlopen(API).read()

In [140]:
### 크롤링
from bs4 import BeautifulSoup # text => html
# 스크래핑
html = """  
<html><body>
  <h1>스크레이핑이란?</h1>
  <p>웹 페이지를 분석하는 것</p>
  <p>원하는 부분을 추출하는 것</p>
</body></html>
"""
# HTML 분석하기
soup = BeautifulSoup(html, 'html.parser') # text를 html변환
h1 = soup.html.h1
print(h1)
print(h1.string)
p1 = soup.html.p
print(p1)
print(p1.string)
p2 = soup.html.p.next_sibling.next_sibling
print(p2)
print(p2.string)


<h1>스크레이핑이란?</h1>
스크레이핑이란?
<p>웹 페이지를 분석하는 것</p>
웹 페이지를 분석하는 것
<p>원하는 부분을 추출하는 것</p>
원하는 부분을 추출하는 것


In [146]:
html = """  
<html><body>
  <h1 id='title'>스크레이핑이란?</h1>
  <p id='body'>웹 페이지를 분석하는 것</p>
  <p>원하는 부분을 추출하는 것</p>
</body></html>
"""
soup = BeautifulSoup(html, 'html.parser') 
title = soup.find(id="title")
print(title)
print(title.string)
body = soup.find(id="body")
print(body)
print(body.string)
h1 = soup.find("h1")
print(h1)
print(h1.string)

<h1 id="title">스크레이핑이란?</h1>
스크레이핑이란?
<p id="body">웹 페이지를 분석하는 것</p>
웹 페이지를 분석하는 것
<h1 id="title">스크레이핑이란?</h1>
스크레이핑이란?


In [150]:
html = """  
<html><body>
  <h1 id='title'>스크레이핑이란?</h1>
  <p id='body'>웹 페이지를 분석하는 것</p>
  <p><a href='a.html' id='link'>원하는 부분을 추출하는 것</a></p>
</body></html>
"""
soup = BeautifulSoup(html, 'html.parser') 
a = soup.html.a
print(a)
print(a.string)
attr = a.attrs
print(attr)
print(attr["href"])

<a href="a.html" id="link">원하는 부분을 추출하는 것</a>
원하는 부분을 추출하는 것
{'href': 'a.html', 'id': 'link'}
a.html


In [167]:
import urllib.request as req # 스크래핑
from bs4 import BeautifulSoup # 크롤링
url = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
data = urllib.request.urlopen(url).read() # byte
soup = BeautifulSoup(data, "html.parser")
title = soup.title
print(title)
print(title.string)
title = soup.find("title")
print(title)
print(title.string)
wf = soup.find("wf")
print(wf.string)

<title>기상청 육상 중기예보</title>
기상청 육상 중기예보
<title>기상청 육상 중기예보</title>
기상청 육상 중기예보
○ (강수) 8일(화) 강원영동에, 9일(수)~10일(목) 강원영동과 경상권에 비가 오겠습니다.<br />○ (기온) 8일(화)~9일(수) 아침 기온은 24~27도, 낮 기온은 28~35도로 평년(최저기온 22~24도, 최고기온 29~33도)보다 높겠습니다.<br />          10일(목)~15일(화) 아침 기온은 22~26도, 낮 기온은 29~33도로 평년과 비슷하겠습니다.<br />○ (해상) 제주도해상은 9일(수)까지, 남해동부해상은 10일(목)까지 물결이 1.0~4.0m(남해동부해상 9일(수) 5.0m 이상)로 매우 높게 일겠으며, <br />          동해상은 8일(화)~11일(금) 물결이 1.0~4.0m(9일(수)~10일(목) 5.0m 이상)로 매우 높게 일겠습니다.<br /><br />* 이번 예보기간 무더위가 지속되는 가운데, 제6호 태풍(카눈)의 이동경로에 따라 강수구역과 시점이 변경될 가능성과 내륙을 중심으로 소나기가 내릴 가능성이 있겠으니, 앞으로 발표되는 최신 예보를 참고하기 바랍니다.


In [171]:
from bs4 import BeautifulSoup
text = """
<html><body>
<h1>위키북스 도서1111111</h1>
<div>
    <h1>zxvsxdv</h1>
</div>
<div id="meigen">
  <h1>위키북스 도서</h1>
  <ul class="items">
    <li>유니티 게임 이펙트 입문</li>
    <li>스위프트로 시작하는 아이폰 앱 개발 교과서</li>
    <li>모던 웹사이트 디자인의 정석</li>
  </ul>
</div>
</body></html>
"""
soup = BeautifulSoup(text, "html.parser")
h1 = soup.html.h1
print(h1)
h2 = soup.find("h1")
print(h2)
print(h2.string)
h3 = soup.find("h1").string
print(h3)
id1 = soup.find(id="meigen")
print(id1)
### css selector(css 선택자)
h12 = soup.select_one("div > h1").string
print(h12)
h13 = soup.select_one("div#meigen > h1")
print(h13)
li1 = soup.select_one("div#meigen > ul.items > li")
print(li1)
li2 = soup.select("div#meigen > ul.items > li")
print(li2)
for str1 in li2:
    print(str1.string)

<h1>위키북스 도서1111111</h1>
<h1>위키북스 도서1111111</h1>
위키북스 도서1111111
위키북스 도서1111111
<div id="meigen">
<h1>위키북스 도서</h1>
<ul class="items">
<li>유니티 게임 이펙트 입문</li>
<li>스위프트로 시작하는 아이폰 앱 개발 교과서</li>
<li>모던 웹사이트 디자인의 정석</li>
</ul>
</div>
zxvsxdv
<h1>위키북스 도서</h1>
<li>유니티 게임 이펙트 입문</li>
[<li>유니티 게임 이펙트 입문</li>, <li>스위프트로 시작하는 아이폰 앱 개발 교과서</li>, <li>모던 웹사이트 디자인의 정석</li>]
유니티 게임 이펙트 입문
스위프트로 시작하는 아이폰 앱 개발 교과서
모던 웹사이트 디자인의 정석


In [182]:
import urllib.request as req # 스크래핑
from bs4 import BeautifulSoup # 크롤링
url = "http://finance.naver.com/marketindex/"
res  = req.urlopen(url)
soup = BeautifulSoup(res, "html.parser") 
pri = soup.select_one("#exchangeList > li.on > a.head.usd > div > span.value")
print(pri.string)
prices = soup.select("div span.value")
print(prices)
for price in prices:
    print(price.string)

1,308.00
[<span class="value">1,308.00</span>, <span class="value">922.69</span>, <span class="value">1,439.98</span>, <span class="value">181.97</span>, <span class="value">141.8000</span>, <span class="value">1.1021</span>, <span class="value">1.2755</span>, <span class="value">101.8300</span>, <span class="value">82.82</span>, <span class="value">1675.34</span>, <span class="value">1976.1</span>, <span class="value">81650.46</span>]
1,308.00
922.69
1,439.98
181.97
141.8000
1.1021
1.2755
101.8300
82.82
1675.34
1976.1
81650.46


In [201]:
import requests  # 스크래핑
from bs4 import BeautifulSoup # 크롤링
import pandas # 데이터분석
import matplotlib as mpl 
import matplotlib.pyplot as plt # 시각화
url = "https://www.weather.go.kr/w/obs-climate/land/city-obs.do"
source = requests.get(url)
soup = BeautifulSoup(source.content, "html.parser")
#pint(soup)
table = soup.find("table",{'class':'table-col'})

data = []

for tr in table.find_all('tr'):
    tds = list(tr.find_all("td"))
    for td in tds:
        if td.find('a'):
            point = td.find('a').text 
            temp =  tds[5].string
            humidity = tds[9].string
            data.append([point,temp,humidity])

#데이터 처리
with open('weather.csv','w', encoding='utf-8') as f:
    f.write('지역, 온도, 습도\n')
    for i in data:
        f.write("{0},{1},{2}\n".format(i[0],i[1],i[2]))

# 분석할 데이터 저장
df = pandas.read_csv("weather.csv", index_col ="지역", encoding="utf-8")
df
city_df = df.loc[['서울','인천','대전','대구','광주','부산','울산']]
city_df

font_name = mpl.font_manager.FontProperties(fname="C:\Windows\Fonts\malgun.ttf").get_name()
mpl.rc('font', family=font_name)

ax = city_df.plot(kind="bar", title="날씨", figsize=(12,4))
plt.show()

온도   습도
지역            
강릉   37.5   45
강진군  35.8   52
강화   31.0   67
거제   33.3   56
거창   33.8   56
..    ...  ...
합천   35.8   47
해남   33.6   60
홍성   32.7   66
홍천   35.3   48
흑산도  30.0   69

[97 rows x 2 columns]

In [202]:
# numpy
!pip install numpy
# python 기본자료형 : 정수, 실수, 문자열, 리스트, 튜플, 딕셔너리, 집합, 부울
# numpy : 배열자료형 : 숫자만 다루는 배열

In [233]:
import numpy
num = numpy.random.randint(10)
print(num)

5


In [234]:
import numpy as np
num = np.random.randint(10)
print(num)

1


In [236]:
num= np.random.randint(10, size=6) # 1차원 배열
print(num)

[5 6 0 3 8 2]


In [237]:
l = [5, 6, 0, 3, 8, 2]
print(l)
print(num) 

[5, 6, 0, 3, 8, 2]
[5 6 0 3 8 2]


In [240]:
# [5, 6, 0, 3, 8, 2]
#  0  1  2  3  4  5
# [5 6 0 3 8 2]
#  0 1 2 3 4 5
print(l[1])
print(num[1])
# num = [5 6 0 3 8 2] (x)
print(l[2:4])
print(num[2:4])

6
6
[0, 3]
[0 3]


In [243]:
# 2차원 : 1차원의 집합체이다.
num2 = np.random.randint(10, size=(2, 6)) 
print(num2)
print(num)

[[7 7 1 7 9 5]
 [4 7 2 7 1 3]]
[5 6 0 3 8 2]


In [244]:
l2 = [[7, 7, 1, 7, 9, 5],[4, 7, 2, 7, 1, 3]]
print(l2)
print(num2)

[[7, 7, 1, 7, 9, 5], [4, 7, 2, 7, 1, 3]]
[[7 7 1 7 9 5]
 [4 7 2 7 1 3]]


In [251]:
'''
[[7 7 1 7 9 5]       [4 7 2 7 1 3]]
     0행                   1행 
  0열1열2열...        0열1열2열...

[[7, 7, 1, 7, 9, 5], [4, 7, 2, 7, 1, 3]]
        0index            1index
  0index,1index...    0index,1index...
'''
print(num2[0])
print(l2[0])
print(num2[1])
print(l2[1])
print(num2[1][2]) # 1행2열
print(l2[1][2])

[7 7 1 7 9 5]
[7, 7, 1, 7, 9, 5]
[4 7 2 7 1 3]
[4, 7, 2, 7, 1, 3]
2
2


In [266]:
print(num)
print(l)
'''
    [5, 6, 0, 3, 8, 2]
     0  1  2  3  4  5
    -6  5  4  3  2  1
    [5 6 0 3 8 2]
     0 1 2 3 4 5
    -6 5 4 3 2 1 
'''
print(l[-4])
print(num[-4])
print(l[2:4])
print(num[2:4])
print(l[0::2])
print(num[0::2])
print(l[::2])
print(num[::2])
print(l[:])
print(num[:])
print(l[::-1])
print(num[::-1])
print(l[3])
l[3] = 10
print(l)
print(num[3])
num[3] =  10
print(num)

[5 6 0 3 8 2]
[5, 6, 0, 10, 8, 2]
0
0
[0, 10]
[0 3]
[5, 0, 8]
[5 0 8]
[5, 0, 8]
[5 0 8]
[5, 6, 0, 10, 8, 2]
[5 6 0 3 8 2]
[2, 8, 10, 0, 6, 5]
[2 8 3 0 6 5]
10
[5, 6, 0, 10, 8, 2]
3
[ 5  6  0 10  8  2]


In [274]:
print(l2)
print(num2)
'''
[[7, 7, 1, 7, 9, 5], [4, 7, 2, 7, 1, 3]]
        0                   1
       -2                  -1
  0  1  2  3  4  5    0  1  2  3  4  5
 -6  5  4  3  2  1   -6  5  4  3  2  1
[[7 7 1 7 9 5]  [4 7 2 7 1 3]]
        0              1
        -2             -1
  0 1 2 3 4 5    0 1 2 3 4 5
 -6 5 4 3 2 1   -6 5 4 3 2 1
'''
print(l2[0][2]) # 리스트표기
print(num2[0][2]) # 리스트 표기
print(num2[0, 2]) # 배열표기
# print(l2[0, 2]) (x)
print(l2[-2][-4])
print(num2[-2][-4])
print(num2[-2 , -4])
# print(l2[-2, -4]) (X)

[[7, 7, 1, 7, 9, 5], [4, 7, 2, 7, 1, 3]]
[[7 7 1 7 9 5]
 [4 7 2 7 1 3]]
1
1
1
1
1
1


In [275]:
num3 = np.random.randint(10, size=(3,4))
print(num3)

[[4 0 6 6]
 [4 3 8 9]
 [7 4 7 5]]


In [278]:
l3 = [[4, 0, 6, 6],
 [4, 3, 8, 9],
 [7, 4, 7, 5]]
print(l)

[[4, 0, 6, 6], [4, 3, 8, 9], [7, 4, 7, 5]]


In [281]:
'''
  0열1열2열3열
[[4   0  6  6]    0행
 [4   3  8  9]    1행
 [7   4  7  5]]   2행
 
 0index
[[4, 0, 6, 6],  0index
 [4, 3, 8, 9],  1index
 [7, 4, 7, 5]]  2index
'''
print(l3[0]) # 0index
print(num3[0]) #0행(row)
print(l3[1][1:3])
print(num3[1][1:3])
print(num3[1, 1:3])

[4, 0, 6, 6]
[4 0 6 6]
[3, 8]
[3 8]
[3 8]


In [306]:
'''
  0열1열2열3열
[[4   0  6  6]    0행
 [4   3  8  9]    1행
 [7   4  7  5]]   2행
 
 0index
[[4, 0, 6, 6],  0index
 [4, 3, 8, 9],  1index
 [7, 4, 7, 5]]  2index
'''
print(l3[0][1:3])
print(l3[1][1:3])
print(l3[0:2][1:3])
print(num3[0][1:3])
print(num3[1][1:3])
print(num3[0:2][1:3])
print(num3[0:2, 1:3])
print(num3[0][0])
print(num3[1][0])
print(num3[2][0])
print(num3[0:3][0]) # x
print(num3[0:3, 0])
print(l3[:][:])
print(num3[:][:])
print(l3[:][0]) # x
print(num3[:][0]) # x
print(num3[: , 0])
print(num3[: , 3])
# print(num3[:][3])
print(l3[0][1])
print(l3[1][1])
print(l3[2][1])
print(l3[0:3][1]) # (x)
print(num3[0][1])
print(num3[1][1])
print(num3[2][1])
print(num3[0:3][1]) # (x)
print(num3[0:3 , 1])

[0, 6]
[3, 8]
[[4, 3, 8, 9]]
[0 6]
[3 8]
[[4 3 8 9]]
[[0 6]
 [3 8]]
4
4
7
[4 0 6 6]
[4 4 7]
[[4, 0, 6, 6], [4, 3, 8, 9], [7, 4, 7, 5]]
[[4 0 6 6]
 [4 3 8 9]
 [7 4 7 5]]
[4, 0, 6, 6]
[4 0 6 6]
[4 4 7]
[6 9 5]
0
3
4
[4, 3, 8, 9]
0
3
4
[4 3 8 9]
[0 3 4]


In [309]:
print(l3[0:3][0:2])
print(num3[0:3][0:2])
print(num3[0:3, 0:2])

[[4, 0, 6, 6], [4, 3, 8, 9]]
[[4 0 6 6]
 [4 3 8 9]]
[[4 0]
 [4 3]
 [7 4]]


In [326]:
print(l3[:][::2])
print(num3[:][::2])
print(num3[: , ::2])

print(l3[::2][:]) #x
print(num3[::2][:]) #x
print(num3[::2, :])

print(l3[::2][::2]) #x
print(num3[::2][::2]) #x
print(num3[::2 , ::2])

print(l3[:][::-1]) # x
print(num3[:][::-1]) # x
print(num3[: , ::-1])

print(num3[::-1 , :])
print(num3[::-1, ::-1])

[[4, 0, 6, 6], [7, 4, 7, 5]]
[[4 0 6 6]
 [7 4 7 5]]
[[4 6]
 [4 8]
 [7 7]]
[[4, 0, 6, 6], [7, 4, 7, 5]]
[[4 0 6 6]
 [7 4 7 5]]
[[4 0 6 6]
 [7 4 7 5]]
[[4, 0, 6, 6]]
[[4 0 6 6]]
[[4 6]
 [7 7]]
[[7, 4, 7, 5], [4, 3, 8, 9], [4, 0, 6, 6]]
[[7 4 7 5]
 [4 3 8 9]
 [4 0 6 6]]
[[6 6 0 4]
 [9 8 3 4]
 [5 7 4 7]]
[[7 4 7 5]
 [4 3 8 9]
 [4 0 6 6]]
[[5 7 4 7]
 [9 8 3 4]
 [6 6 0 4]]


In [332]:
print(l3)
print(l3[0][2])
l3[0][2] = 20
print(num3)
print(num3[0][2])
print(num3[0 , 2])
num3[0][2] = 20 # (x)
num3[0 , 2] = 20
print(num3)

[[4, 0, 20, 6], [4, 3, 8, 9], [7, 4, 7, 5]]
20
[[4 0 6 6]
 [4 3 8 9]
 [7 4 7 5]]
6
6
[[ 4  0 20  6]
 [ 4  3  8  9]
 [ 7  4  7  5]]


In [343]:
### 배열을 만드는 방법
i = np.random.randint(10, size=(3, 4))
print(i)
# arange()
print(np.arange(9)) #[0 1 2 3 4 5 6 7 8]
i2 = np.arange(9)
print(i2)
i3 = np.arange(9).reshape(3,3)
print(i3)
i4 = np.arange(12)
print(i4)
i5 = np.arange(12).reshape(3,4)
#i5 = np.arange(11).reshape(3,4)
i5 = np.arange(12).reshape(4,3)
i6 = np.arange(11, 20).reshape(3,3)
print(i6)
print(np.arange(1,4))
i7 = np.arange(1,4).reshape(1,3)
print(i7)
i8 = np.arange(1,4).reshape(3,1)
print(i8)

[[8 8 7 5]
 [4 5 2 9]
 [8 4 6 1]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [350]:
# array()
# 2,5,7
i9 = np.array([2,5,7])
print(i9)
i10 = np.array((2,5,7))
print(i10)
# 2차원
#     열
# [[1 2 3],    0행
#  [4 5 6],    1행
#  [7 8 9]]    2행
#    
i11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i11)
i12 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[11,12,13],[14,15,16],[17,18,19]],
                [[21,22,23],[24,25,26],[27,28,29]]])
print(i12)
'''
   열
[[[1 2 3]   행
  [4 5 6]      0면
  [7 8 9]]

 [[1 2 3]
  [4 5 6]      1면
  [7 8 9]]]
'''
print()

[2 5 7]
[2 5 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]



In [354]:
l11 = [1,2,3]
l12 = [3,2,1]
l13 = l11 + l12
print(l13)
l14 = []
i = 0
while i < len(l11):
    l14.append(l11[i] + l12[i])
    i +=1
print(l14)

[1, 2, 3, 3, 2, 1]
[4, 4, 4]


In [362]:
x = np.array([1, 2, 3]) # 1차원 배열
y = np.array([3, 2, 1]) # 1차원 배열
z = x + y
print(z)
z = np.concatenate((x , y))
print(z)
v = [99,99,99]
z = np.concatenate((x,y,v))
print(z)
z = np.concatenate(([1,2,3],[3,2,1],v))
print(z)
l1 =[1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
z  = np.concatenate((l1,l2,l3))
print(z)
z = np.concatenate(([1,2,3],[4],[5,6,7,8,9]))
print(z)

[4 4 4]
[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[ 1  2  3  3  2  1 99 99 99]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [376]:
# 2차원 배열 붙이기
x2 = np.array([1, 2, 3])   # 1차원 배열
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]]) # 2차원 배열
grid1 = np.array([[9, 8, 7], 
                 [6, 5, 4]]) # 2차원 배열
print(x2)
print(grid)
print(grid1)
# z = np.concatenate((x2, grid), axis=1)
# 차원이 다르면 concatenate함수를 사용할 수 없다.
z = np.concatenate((grid, grid1)) # axis=0은 기본설정
print(z)
z = np.concatenate((grid, grid1), axis=0) # x축
print(z)
z = np.concatenate((grid, grid1), axis=1) # y축
print(z)

# 차원이 다른 경우 : vstack(열의 차원이 일치), hstack(행의 차원이 일치)
z = np.vstack((x2 , grid))
print(z)
grid3 = np.array([[1,2],[3,4]])
print(grid3)
z = np.hstack((grid, grid3))
print(z)

[1 2 3]
[[9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]
 [9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]
 [9 8 7]
 [6 5 4]]
[[9 8 7 9 8 7]
 [6 5 4 6 5 4]]
[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[1 2]
 [3 4]]
[[9 8 7 1 2]
 [6 5 4 3 4]]
